
version: '3'

services:
  vue-ui:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
       - ./app:/usr/src/app
       - /usr/src/app/node_modules
    # command: bash -c "vue ui -H 0.0.0.0"
    command: ["npm", "run", "serve"]
