version: '3.8'

services:
  front-end:
    build:
      context: .
      dockerfile: ./docker-config/front-end/Dockerfile
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000 # vue ui
      - 8080:8080 # vue dev
    volumes:
      - ./:/app
    command: bash -c "vue ui -H 0.0.0.0"
